#!/bin/bash

if [ -z {WDY_XBUILD_ROOT} ]; then
	echo "WDY_XBUILD_ROOT not set!"
	exit 1
fi

set -e

DIR=$(readlink -f $(dirname $0))

ARMV7_CMAKE_FLAGS="-DWITH_ACLE=OFF -DWITH_UNALIGNED=OFF -DUNALIGNED_OK=OFF"
${WDY_XBUILD_ROOT}/bin/cmake-android-build "${DIR}" -DZLIB_COMPAT=TRUE -DBUILD_SHARED_LIBS=YES 

${WDY_XBUILD_ROOT}/bin/prepare_libraries.sh


